"""tabla usuario

Revision ID: 0e8b5ef09b33
Revises: 636cc28c723e
Create Date: 2025-11-10 16:59:05.838353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8b5ef09b33'
down_revision = '636cc28c723e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario'),
    sa.UniqueConstraint('usuario', name='uq_usuario_usuario')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index('idx_usuario_usuario', ['usuario'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index('idx_usuario_usuario')

    op.drop_table('usuario')
    # ### end Alembic commands ###
