"""se crearon las ttablas actuacion, orden de trabajo e la relacion con inspectores

Revision ID: 140e3c6aae26
Revises: 1967f80e0a93
Create Date: 2025-11-10 00:25:00.953411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140e3c6aae26'
down_revision = '1967f80e0a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orden_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=6), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orden_trabajo', schema=None) as batch_op:
        batch_op.create_index('idx_ot_numero', ['numero'], unique=False)

    op.create_table('actuacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('orden_trabajo_id', sa.Integer(), nullable=True),
    sa.Column('establecimiento_domicilio_id', sa.Integer(), nullable=True),
    sa.Column('contraproducencia', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['establecimiento_domicilio_id'], ['establecimiento_domicilio.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['orden_trabajo_id'], ['orden_trabajo.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orden_trabajo_id', name='uq_act_ot')
    )
    with op.batch_alter_table('actuacion', schema=None) as batch_op:
        batch_op.create_index('idx_act_est_dom', ['establecimiento_domicilio_id'], unique=False)
        batch_op.create_index('idx_act_fecha', ['fecha'], unique=False)
        batch_op.create_index('idx_act_tipo', ['tipo'], unique=False)

    op.create_table('actuacion_inspector',
    sa.Column('actuacion_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('asignado_en', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actuacion_id'], ['actuacion.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspector_id'], ['inspector.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('actuacion_id', 'inspector_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actuacion_inspector')
    with op.batch_alter_table('actuacion', schema=None) as batch_op:
        batch_op.drop_index('idx_act_tipo')
        batch_op.drop_index('idx_act_fecha')
        batch_op.drop_index('idx_act_est_dom')

    op.drop_table('actuacion')
    with op.batch_alter_table('orden_trabajo', schema=None) as batch_op:
        batch_op.drop_index('idx_ot_numero')

    op.drop_table('orden_trabajo')
    # ### end Alembic commands ###
