"""turno e inspectores_bien

Revision ID: 1967f80e0a93
Revises: d4fe9f92faa8
Create Date: 2025-11-09 05:51:52.344310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1967f80e0a93'
down_revision = 'd4fe9f92faa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('hora_desde', sa.Time(), nullable=False),
    sa.Column('hora_hasta', sa.Time(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('turno', schema=None) as batch_op:
        batch_op.create_index('idx_turno_horas', ['hora_desde', 'hora_hasta'], unique=False)

    op.create_table('inspector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legajo', sa.Integer(), nullable=False),
    sa.Column('apellido', sa.String(length=128), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['turno_id'], ['turno.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legajo')
    )
    with op.batch_alter_table('inspector', schema=None) as batch_op:
        batch_op.create_index('idx_inspector_apellido', ['apellido'], unique=False)
        batch_op.create_index('idx_inspector_apynom', ['apellido', 'nombre'], unique=False)
        batch_op.create_index('idx_inspector_turno', ['turno_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspector', schema=None) as batch_op:
        batch_op.drop_index('idx_inspector_turno')
        batch_op.drop_index('idx_inspector_apynom')
        batch_op.drop_index('idx_inspector_apellido')

    op.drop_table('inspector')
    with op.batch_alter_table('turno', schema=None) as batch_op:
        batch_op.drop_index('idx_turno_horas')

    op.drop_table('turno')
    # ### end Alembic commands ###
