"""acta clausura y de decomiso creadas con sus tabals catalogos

Revision ID: 325e17398976
Revises: 4e25de2fe835
Create Date: 2025-11-10 01:13:04.399899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '325e17398976'
down_revision = '4e25de2fe835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motivo_clausura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', name='uq_motivo_clausura_nombre')
    )
    with op.batch_alter_table('motivo_clausura', schema=None) as batch_op:
        batch_op.create_index('idx_motivo_clausura_nombre', ['nombre'], unique=False)

    op.create_table('acta_clausura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_acta', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.SmallInteger(), nullable=False),
    sa.Column('actuacion_id', sa.Integer(), nullable=False),
    sa.Column('motivo_id', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actuacion_id'], ['actuacion.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['motivo_id'], ['motivo_clausura.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actuacion_id'),
    sa.UniqueConstraint('numero_acta', 'anio', name='uq_ac_numero_anio')
    )
    with op.batch_alter_table('acta_clausura', schema=None) as batch_op:
        batch_op.create_index('idx_ac_anio', ['anio'], unique=False)
        batch_op.create_index('idx_ac_motivo', ['motivo_id'], unique=False)
        batch_op.create_index('idx_ac_numero', ['numero_acta'], unique=False)

    op.create_table('acta_decomiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_acta', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.SmallInteger(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('actuacion_id', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actuacion_id'], ['actuacion.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actuacion_id'),
    sa.UniqueConstraint('numero_acta', 'anio', name='uq_ad_numero_anio')
    )
    with op.batch_alter_table('acta_decomiso', schema=None) as batch_op:
        batch_op.create_index('idx_ad_anio', ['anio'], unique=False)
        batch_op.create_index('idx_ad_numero', ['numero_acta'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acta_decomiso', schema=None) as batch_op:
        batch_op.drop_index('idx_ad_numero')
        batch_op.drop_index('idx_ad_anio')

    op.drop_table('acta_decomiso')
    with op.batch_alter_table('acta_clausura', schema=None) as batch_op:
        batch_op.drop_index('idx_ac_numero')
        batch_op.drop_index('idx_ac_motivo')
        batch_op.drop_index('idx_ac_anio')

    op.drop_table('acta_clausura')
    with op.batch_alter_table('motivo_clausura', schema=None) as batch_op:
        batch_op.drop_index('idx_motivo_clausura_nombre')

    op.drop_table('motivo_clausura')
    # ### end Alembic commands ###
