"""expediente import

Revision ID: 424dc0c203de
Revises: 602ad7e18275
Create Date: 2025-11-10 01:02:35.492292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424dc0c203de'
down_revision = '602ad7e18275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expediente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_expediente', sa.String(length=30), nullable=False),
    sa.Column('anio', sa.SmallInteger(), nullable=False),
    sa.Column('actuacion_id', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actuacion_id'], ['actuacion.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actuacion_id'),
    sa.UniqueConstraint('numero_expediente', 'anio', name='uq_exp_numero_anio')
    )
    with op.batch_alter_table('expediente', schema=None) as batch_op:
        batch_op.create_index('idx_exp_anio', ['anio'], unique=False)
        batch_op.create_index('idx_exp_numero', ['numero_expediente'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expediente', schema=None) as batch_op:
        batch_op.drop_index('idx_exp_numero')
        batch_op.drop_index('idx_exp_anio')

    op.drop_table('expediente')
    # ### end Alembic commands ###
