"""se crearon las ttablas acta de comprobacion con sus relacionales

Revision ID: 4da461215924
Revises: 140e3c6aae26
Create Date: 2025-11-10 00:51:48.439581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da461215924'
down_revision = '140e3c6aae26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero', name='uq_articulo_numero')
    )
    with op.batch_alter_table('articulo', schema=None) as batch_op:
        batch_op.create_index('idx_art_numero', ['numero'], unique=False)

    op.create_table('acta_comprobacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_acta', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.SmallInteger(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=True),
    sa.Column('actuada_dos_veces', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_acta', 'anio', name='uq_acp_numero_anio')
    )
    with op.batch_alter_table('acta_comprobacion', schema=None) as batch_op:
        batch_op.create_index('idx_acp_articulo', ['articulo_id'], unique=False)
        batch_op.create_index('idx_acp_flags', ['actuada_dos_veces'], unique=False)

    op.create_table('oficio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_oficio', sa.String(length=30), nullable=False),
    sa.Column('anio', sa.SmallInteger(), nullable=False),
    sa.Column('causa', sa.Integer(), nullable=True),
    sa.Column('acta_comprobacion_id', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['acta_comprobacion_id'], ['acta_comprobacion.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oficio', schema=None) as batch_op:
        batch_op.create_index('idx_ofi_acta', ['acta_comprobacion_id'], unique=False)
        batch_op.create_index('idx_ofi_anio', ['anio'], unique=False)
        batch_op.create_index('idx_ofi_num', ['numero_oficio'], unique=False)

    op.create_table('actuacion_comprobacion',
    sa.Column('actuacion_id', sa.Integer(), nullable=False),
    sa.Column('acta_comprobacion_id', sa.Integer(), nullable=False),
    sa.Column('contexto', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['acta_comprobacion_id'], ['acta_comprobacion.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['actuacion_id'], ['actuacion.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actuacion_id', 'acta_comprobacion_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actuacion_comprobacion')
    with op.batch_alter_table('oficio', schema=None) as batch_op:
        batch_op.drop_index('idx_ofi_num')
        batch_op.drop_index('idx_ofi_anio')
        batch_op.drop_index('idx_ofi_acta')

    op.drop_table('oficio')
    with op.batch_alter_table('acta_comprobacion', schema=None) as batch_op:
        batch_op.drop_index('idx_acp_flags')
        batch_op.drop_index('idx_acp_articulo')

    op.drop_table('acta_comprobacion')
    with op.batch_alter_table('articulo', schema=None) as batch_op:
        batch_op.drop_index('idx_art_numero')

    op.drop_table('articulo')
    # ### end Alembic commands ###
