"""acta_inspeccion creada

Revision ID: 4e25de2fe835
Revises: 424dc0c203de
Create Date: 2025-11-10 01:06:59.635828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e25de2fe835'
down_revision = '424dc0c203de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acta_inspeccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_acta', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.SmallInteger(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('actuacion_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actuacion_id'], ['actuacion.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actuacion_id'),
    sa.UniqueConstraint('numero_acta', 'anio', name='uq_ai_numero_anio')
    )
    with op.batch_alter_table('acta_inspeccion', schema=None) as batch_op:
        batch_op.create_index('idx_ai_anio', ['anio'], unique=False)
        batch_op.create_index('idx_ai_numero', ['numero_acta'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acta_inspeccion', schema=None) as batch_op:
        batch_op.drop_index('idx_ai_numero')
        batch_op.drop_index('idx_ai_anio')

    op.drop_table('acta_inspeccion')
    # ### end Alembic commands ###
