"""domicilio,barrio,distrito

Revision ID: 5236d4198e64
Revises: 82eb84f9a64b
Create Date: 2025-11-08 21:21:45.905295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5236d4198e64'
down_revision = '82eb84f9a64b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distrito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('geom_wkt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('barrio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('distrito_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['distrito_id'], ['distrito.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('barrio', schema=None) as batch_op:
        batch_op.create_index('idx_barrio_distrito', ['distrito_id'], unique=False)

    op.create_table('domicilio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calle', sa.String(length=128), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('local', sa.String(length=128), nullable=True),
    sa.Column('cp', sa.String(length=10), nullable=True),
    sa.Column('barrio_id', sa.Integer(), nullable=True),
    sa.Column('distrito_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lon', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['barrio_id'], ['barrio.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['distrito_id'], ['distrito.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domicilio', schema=None) as batch_op:
        batch_op.create_index('idx_dom_barrio', ['barrio_id'], unique=False)
        batch_op.create_index('idx_dom_busqueda', ['calle', 'numero'], unique=False)
        batch_op.create_index('idx_dom_cp', ['cp'], unique=False)
        batch_op.create_index('idx_dom_distrito', ['distrito_id'], unique=False)
        batch_op.create_index('idx_dom_geo', ['lat', 'lon'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domicilio', schema=None) as batch_op:
        batch_op.drop_index('idx_dom_geo')
        batch_op.drop_index('idx_dom_distrito')
        batch_op.drop_index('idx_dom_cp')
        batch_op.drop_index('idx_dom_busqueda')
        batch_op.drop_index('idx_dom_barrio')

    op.drop_table('domicilio')
    with op.batch_alter_table('barrio', schema=None) as batch_op:
        batch_op.drop_index('idx_barrio_distrito')

    op.drop_table('barrio')
    op.drop_table('distrito')
    # ### end Alembic commands ###
