"""notificacion, motivos, notificacion_motivo y actuacion_notificacion

Revision ID: 602ad7e18275
Revises: 4da461215924
Create Date: 2025-11-10 00:56:06.437554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602ad7e18275'
down_revision = '4da461215924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motivo_notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', name='uq_motivo_notif_nombre')
    )
    with op.batch_alter_table('motivo_notificacion', schema=None) as batch_op:
        batch_op.create_index('idx_motivo_notif_nombre', ['nombre'], unique=False)

    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_acta', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.SmallInteger(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_acta', 'anio', name='uq_an_numero_anio')
    )
    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.create_index('idx_an_anio', ['anio'], unique=False)
        batch_op.create_index('idx_an_numero', ['numero_acta'], unique=False)

    op.create_table('notificacion_motivo',
    sa.Column('notificacion_id', sa.Integer(), nullable=False),
    sa.Column('motivo_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['motivo_id'], ['motivo_notificacion.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['notificacion_id'], ['notificacion.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notificacion_id', 'motivo_id'),
    sa.UniqueConstraint('notificacion_id', 'motivo_id', name='uq_notif_motivo')
    )
    op.create_table('actuacion_notificacion',
    sa.Column('actuacion_id', sa.Integer(), nullable=False),
    sa.Column('notificacion_id', sa.Integer(), nullable=False),
    sa.Column('contexto', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['actuacion_id'], ['actuacion.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notificacion_id'], ['notificacion.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('actuacion_id', 'notificacion_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actuacion_notificacion')
    op.drop_table('notificacion_motivo')
    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.drop_index('idx_an_numero')
        batch_op.drop_index('idx_an_anio')

    op.drop_table('notificacion')
    with op.batch_alter_table('motivo_notificacion', schema=None) as batch_op:
        batch_op.drop_index('idx_motivo_notif_nombre')

    op.drop_table('motivo_notificacion')
    # ### end Alembic commands ###
