"""tabla relevamiento

Revision ID: 636cc28c723e
Revises: 325e17398976
Create Date: 2025-11-10 16:32:11.750589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636cc28c723e'
down_revision = '325e17398976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relevamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domicilio_id', sa.Integer(), nullable=False),
    sa.Column('rubro_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['domicilio_id'], ['domicilio.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domicilio_id'),
    sa.UniqueConstraint('domicilio_id', 'rubro_id', name='uq_rel_dom_rubro'),
    sa.UniqueConstraint('rubro_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relevamiento')
    # ### end Alembic commands ###
