"""catalogos (documento_tipo, genero) + contribuyente con unique compuesto

Revision ID: 82eb84f9a64b
Revises: d9ec3f74cb51
Create Date: 2025-11-05 17:14:07.737918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82eb84f9a64b'
down_revision = 'd9ec3f74cb51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documento_tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('genero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('contribuyente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apellido', sa.String(length=128), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('doc_tipo_id', sa.Integer(), nullable=True),
    sa.Column('genero_id', sa.Integer(), nullable=True),
    sa.Column('doc_nro', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['doc_tipo_id'], ['documento_tipo.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['genero_id'], ['genero.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_tipo_id', 'doc_nro', name='uq_contrib_doc')
    )
    with op.batch_alter_table('contribuyente', schema=None) as batch_op:
        batch_op.create_index('idx_contrib_apellido_nombre', ['apellido', 'nombre'], unique=False)
        batch_op.create_index('idx_contrib_doc_std', ['doc_tipo_id', 'doc_nro'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contribuyente', schema=None) as batch_op:
        batch_op.drop_index('idx_contrib_doc_std')
        batch_op.drop_index('idx_contrib_apellido_nombre')

    op.drop_table('contribuyente')
    op.drop_table('genero')
    op.drop_table('documento_tipo')
    # ### end Alembic commands ###
