"""establecimiento y sus relaciones

Revision ID: d4fe9f92faa8
Revises: 5236d4198e64
Create Date: 2025-11-09 01:01:54.964240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4fe9f92faa8'
down_revision = '5236d4198e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('establecimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contribuyente_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['contribuyente_id'], ['contribuyente.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('establecimiento', schema=None) as batch_op:
        batch_op.create_index('idx_est_contrib', ['contribuyente_id'], unique=False)
        batch_op.create_index('idx_est_nombre', ['nombre'], unique=False)

    op.create_table('establecimiento_domicilio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('establecimiento_id', sa.Integer(), nullable=False),
    sa.Column('domicilio_id', sa.Integer(), nullable=False),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['domicilio_id'], ['domicilio.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimiento.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('establecimiento_id', 'domicilio_id', 'fecha_desde', name='uq_ed_est_dom_desde')
    )
    with op.batch_alter_table('establecimiento_domicilio', schema=None) as batch_op:
        batch_op.create_index('idx_ed_dom', ['domicilio_id'], unique=False)
        batch_op.create_index('idx_ed_est', ['establecimiento_id'], unique=False)
        batch_op.create_index('idx_ed_vigencia', ['fecha_desde', 'fecha_hasta'], unique=False)

    op.create_table('establecimiento_rubro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('establecimiento_id', sa.Integer(), nullable=False),
    sa.Column('rubro_id', sa.Integer(), nullable=False),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimiento.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('establecimiento_id', 'rubro_id', 'fecha_desde', name='uq_er_est_rubro_desde')
    )
    with op.batch_alter_table('establecimiento_rubro', schema=None) as batch_op:
        batch_op.create_index('idx_er_est', ['establecimiento_id'], unique=False)
        batch_op.create_index('idx_er_rubro', ['rubro_id'], unique=False)
        batch_op.create_index('idx_er_vigencia', ['fecha_desde', 'fecha_hasta'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('establecimiento_rubro', schema=None) as batch_op:
        batch_op.drop_index('idx_er_vigencia')
        batch_op.drop_index('idx_er_rubro')
        batch_op.drop_index('idx_er_est')

    op.drop_table('establecimiento_rubro')
    with op.batch_alter_table('establecimiento_domicilio', schema=None) as batch_op:
        batch_op.drop_index('idx_ed_vigencia')
        batch_op.drop_index('idx_ed_est')
        batch_op.drop_index('idx_ed_dom')

    op.drop_table('establecimiento_domicilio')
    with op.batch_alter_table('establecimiento', schema=None) as batch_op:
        batch_op.drop_index('idx_est_nombre')
        batch_op.drop_index('idx_est_contrib')

    op.drop_table('establecimiento')
    # ### end Alembic commands ###
