"""init rubro_bie

Revision ID: d9ec3f74cb51
Revises: 647b0ee16924
Create Date: 2025-11-05 01:33:17.151543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ec3f74cb51'
down_revision = '647b0ee16924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rubro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
        batch_op.create_index('idx_rubro_activo', ['activo'], unique=False)
        batch_op.create_index('idx_rubro_nombre', ['nombre'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rubro', schema=None) as batch_op:
        batch_op.drop_index('idx_rubro_nombre')
        batch_op.drop_index('idx_rubro_activo')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
