from .acta_clausura import ActaClausura
from .acta_comprobacion import ActaComprobacion
from .acta_decomiso import ActaDecomiso
from .acta_inspeccion import ActaInspeccion
from .actuacion import Actuacion
from .actuacion_comprobacion import ActuacionComprobacion
from .actuacion_inspector import ActuacionInspector
from .actuacion_notificacion import ActuacionNotificacion
from .articulo import Articulo
from .barrio import Barrio
from .contribuyente import Contribuyente
from .distrito import Distrito
from .documento_tipo import DocumentoTipo
from .domicilio import Domicilio
from .establecimiento import Establecimiento
from .establecimiento_domicilio import EstablecimientoDomicilio
from .establecimiento_rubro import EstablecimientoRubro
from .expediente import Expediente
from .genero import Genero
from .inspector import Inspector
from .motivo_clausura import MotivoClausura
from .motivo_notificacion import MotivoNotificacion
from .notificacion import Notificacion
from .notificacion_motivo import NotificacionMotivo
from .oficio import Oficio
from .orden_trabajo import OrdenTrabajo
from .rubro import Rubro
from .turno import Turno
