from .barrio import Barrio
from .contribuyente import Contribuyente
from .distrito import Distrito
from .documento_tipo import DocumentoTipo
from .domicilio import Domicilio
from .establecimiento import Establecimiento
from .establecimiento_domicilio import EstablecimientoDomicilio
from .establecimiento_rubro import EstablecimientoRubro
from .genero import Genero
from .inspector import Inspector
from .rubro import Rubro
from .turno import Turno
