-- Esquema inicial basado en los modelos ORM
-- Formato de conexión recomendado: mysql -u <user> -p

CREATE DATABASE IF NOT EXISTS devvproyectofinal CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE devvproyectofinal;

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS documento_tipo (
  id INT AUTO_INCREMENT PRIMARY KEY,
  codigo VARCHAR(10) NOT NULL UNIQUE,
  nombre VARCHAR(150) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contribuyente (
  id INT AUTO_INCREMENT PRIMARY KEY,
  apellido VARCHAR(128) NOT NULL,
  nombre VARCHAR(128) NOT NULL,
  doc_tipo_id INT NOT NULL,
  doc_nro VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT uq_contrib_doc UNIQUE (doc_tipo_id, doc_nro),
  CONSTRAINT fk_contrib_doc_tipo FOREIGN KEY (doc_tipo_id) REFERENCES documento_tipo(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS rubro (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(128) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS turno (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(128) NOT NULL,
  descripcion TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inspector (
  id INT AUTO_INCREMENT PRIMARY KEY,
  legajo INT NOT NULL UNIQUE,
  apellido VARCHAR(128) NOT NULL,
  nombre VARCHAR(128) NOT NULL,
  turno_id INT NULL,
  email VARCHAR(150) NULL,
  telefono VARCHAR(50) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_inspector_turno (turno_id),
  CONSTRAINT fk_inspector_turno FOREIGN KEY (turno_id) REFERENCES turno(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS orden_trabajo (
  id INT AUTO_INCREMENT PRIMARY KEY,
  numero VARCHAR(6) NOT NULL UNIQUE,
  descripcion TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS distrito (
  id INT AUTO_INCREMENT PRIMARY KEY,
  numero INT NOT NULL,
  nombre VARCHAR(150) NOT NULL,
  UNIQUE KEY uq_distrito_numero (numero)
);

CREATE TABLE IF NOT EXISTS barrio (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  distrito_id INT NULL,
  CONSTRAINT fk_barrio_distrito FOREIGN KEY (distrito_id) REFERENCES distrito(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS domicilio (
  id INT AUTO_INCREMENT PRIMARY KEY,
  calle VARCHAR(128) NOT NULL,
  numero VARCHAR(20) NULL,
  local VARCHAR(128) NULL,
  cp VARCHAR(10) NULL,
  barrio_id INT NULL,
  distrito_id INT NULL,
  lat DECIMAL(9,6) NULL,
  lon DECIMAL(9,6) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_domicilio_barrio FOREIGN KEY (barrio_id) REFERENCES barrio(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_domicilio_distrito FOREIGN KEY (distrito_id) REFERENCES distrito(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS establecimiento (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  contribuyente_id INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_est_contrib FOREIGN KEY (contribuyente_id) REFERENCES contribuyente(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS establecimiento_domicilio (
  id INT AUTO_INCREMENT PRIMARY KEY,
  establecimiento_id INT NOT NULL,
  domicilio_id INT NOT NULL,
  fecha_desde DATE NOT NULL,
  fecha_hasta DATE NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_est_dom_est FOREIGN KEY (establecimiento_id) REFERENCES establecimiento(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_est_dom_dom FOREIGN KEY (domicilio_id) REFERENCES domicilio(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS establecimiento_rubro (
  id INT AUTO_INCREMENT PRIMARY KEY,
  establecimiento_id INT NOT NULL,
  rubro_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_est_rubro_est FOREIGN KEY (establecimiento_id) REFERENCES establecimiento(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_est_rubro_rubro FOREIGN KEY (rubro_id) REFERENCES rubro(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS actuacion (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fecha DATE NOT NULL,
  tipo VARCHAR(20) NOT NULL,
  orden_trabajo_id INT NULL,
  establecimiento_domicilio_id INT NULL,
  contraproducencia TEXT NULL,
  observaciones TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_act_ot (orden_trabajo_id),
  INDEX idx_act_fecha (fecha),
  INDEX idx_act_tipo (tipo),
  CONSTRAINT fk_act_ot FOREIGN KEY (orden_trabajo_id) REFERENCES orden_trabajo(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_act_est_dom FOREIGN KEY (establecimiento_domicilio_id) REFERENCES establecimiento_domicilio(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS actuacion_inspector (
  actuacion_id INT NOT NULL,
  inspector_id INT NOT NULL,
  rol VARCHAR(20) NULL,
  asignado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (actuacion_id, inspector_id),
  CONSTRAINT fk_ai_act FOREIGN KEY (actuacion_id) REFERENCES actuacion(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_ai_insp FOREIGN KEY (inspector_id) REFERENCES inspector(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS acta_inspeccion (
  id INT AUTO_INCREMENT PRIMARY KEY,
  numero_acta VARCHAR(6) NOT NULL,
  anio SMALLINT NOT NULL,
  actuacion_id INT NULL,
  observaciones TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_ai_numero_anio (numero_acta, anio),
  CONSTRAINT fk_ai_act FOREIGN KEY (actuacion_id) REFERENCES actuacion(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS notificacion (
  id INT AUTO_INCREMENT PRIMARY KEY,
  numero_acta VARCHAR(6) NOT NULL,
  anio SMALLINT NOT NULL,
  observaciones TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_an_numero_anio (numero_acta, anio)
);

CREATE TABLE IF NOT EXISTS motivo_notificacion (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(200) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notificacion_motivo (
  notificacion_id INT NOT NULL,
  motivo_id INT NOT NULL,
  orden INT NULL,
  PRIMARY KEY (notificacion_id, motivo_id),
  CONSTRAINT fk_nm_notif FOREIGN KEY (notificacion_id) REFERENCES notificacion(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_nm_motivo FOREIGN KEY (motivo_id) REFERENCES motivo_notificacion(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS acta_comprobacion (
  id INT AUTO_INCREMENT PRIMARY KEY,
  numero_acta VARCHAR(6) NOT NULL,
  anio SMALLINT NOT NULL,
  articulo_id INT NULL,
  actuada_dos_veces BOOLEAN NOT NULL DEFAULT 0,
  observaciones TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_acp_numero_anio (numero_acta, anio)
);

CREATE TABLE IF NOT EXISTS acta_clausura (
  id INT AUTO_INCREMENT PRIMARY KEY,
  numero_acta VARCHAR(6) NOT NULL,
  anio SMALLINT NOT NULL,
  actuacion_id INT NULL,
  motivo_id INT NULL,
  observaciones TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_acl_numero_anio (numero_acta, anio),
  CONSTRAINT fk_acl_act FOREIGN KEY (actuacion_id) REFERENCES actuacion(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS motivo_clausura (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(200) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS acta_decomiso (
  id INT AUTO_INCREMENT PRIMARY KEY,
  numero_acta VARCHAR(6) NOT NULL,
  anio SMALLINT NOT NULL,
  kilos_total DECIMAL(10,2) NULL,
  actuacion_id INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_ad_numero_anio (numero_acta, anio),
  CONSTRAINT fk_ad_act FOREIGN KEY (actuacion_id) REFERENCES actuacion(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS actuacion_notificacion (
  actuacion_id INT NOT NULL,
  notificacion_id INT NOT NULL,
  contexto VARCHAR(50) NULL,
  PRIMARY KEY (actuacion_id, notificacion_id),
  CONSTRAINT fk_an_act FOREIGN KEY (actuacion_id) REFERENCES actuacion(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_an_notif FOREIGN KEY (notificacion_id) REFERENCES notificacion(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS actuacion_comprobacion (
  actuacion_id INT NOT NULL,
  acta_comprobacion_id INT NOT NULL,
  contexto VARCHAR(50) NULL,
  PRIMARY KEY (actuacion_id, acta_comprobacion_id),
  CONSTRAINT fk_ac_act FOREIGN KEY (actuacion_id) REFERENCES actuacion(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_ac_comp FOREIGN KEY (acta_comprobacion_id) REFERENCES acta_comprobacion(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS expediente (
  id INT AUTO_INCREMENT PRIMARY KEY,
  numero_expediente VARCHAR(30) NOT NULL,
  anio SMALLINT NOT NULL,
  actuacion_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_expediente_numero (numero_expediente, anio),
  CONSTRAINT fk_exp_act FOREIGN KEY (actuacion_id) REFERENCES actuacion(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS oficio (
  id INT AUTO_INCREMENT PRIMARY KEY,
  numero VARCHAR(20) NOT NULL,
  anio SMALLINT NOT NULL,
  causa INT NULL,
  acta_comprobacion_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_oficio_numero (numero, anio),
  CONSTRAINT fk_oficio_comp FOREIGN KEY (acta_comprobacion_id) REFERENCES acta_comprobacion(id) ON DELETE CASCADE ON UPDATE CASCADE
);

SET FOREIGN_KEY_CHECKS = 1;
